name: nix

on:
  - push
  - pull_request

jobs:

  build:
    name: build
    runs-on: ubuntu-20.04
    steps:

      - name: checkout
        uses: actions/checkout@v2

      - name: setup-nix-path
        run: |
          echo "NIX_PATH=nixpkgs=$(pwd)/nix/nixpkgs.nix" >> $GITHUB_ENV

      - name: setup-nix
        uses: cachix/install-nix-action@v12

      - name: setup-cachix
        uses: cachix/cachix-action@v8
        with:
          name: ghc-nix

      - name: setup-stack
        run: |
          nix-env -iA \
            nixpkgs.stack

          mkdir ~/.stack
          printf "nix:\n  enable: true\n" > ~/.stack/config.yaml

      - name: materialize
        run: |
          nix-shell \
            --arg withDocs false \
            --arg withDwarf false \
            --arg withNuma false \
            --arg withDtrace false \
            --arg withGrind false \
            --run 'mkdir lib && cd lib && ../utils/make-packages.py && rm -rf ghc' \
            https://github.com/alpmestan/ghc.nix/archive/9223342ec62a2f097e995a4cdec0434540b7c6d9.tar.gz

      - name: boot
        run: |
          stack build --test --no-run-tests asterius
          stack exec ahc-boot
